# your-helm-chart/templates/app-secrets.yaml
# your-helm-chart/templates/app-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets # Matches the deployment's reference
  labels:
    app.kubernetes.io/name: fss-retail-app
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  # Key: session_secret (lowercase 's' as per your successful decode)
  # Value: iloveyou143
  session_secret: aWxvdmV5b3UxNDM=