# your-helm-chart/templates/mongodb-atlas-uri-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-uri-secret # This name matches what your userprofile-deployment.yaml expects
  labels:
    app.kubernetes.io/name: fss-retail-app
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  # The 'uri' key is what your userprofile-deployment.yaml looks for (key: uri)
  # Value: "mongodb+srv://Aryan%20Sodhiya:Aryan%400506@cluster1.2efxjmw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"
  # Base64 encoded:
  # PowerShell: [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("mongodb+srv://Aryan%20Sodhiya:Aryan%400506@cluster1.2efxjmw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"))
  # Linux/Git Bash: echo -n "mongodb+srv://Aryan%20Sodhiya:Aryan%400506@cluster1.2efxjmw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1" | base64
  uri: bW9uZ29kYitzcnY6Ly9hcnlhbnNvZGhpeWExMjEyMjAwMTpBcnlhbiU0MDA1MDZAY2x1c3RlcjEuMmVmeGptdy5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjE=