apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata:
  name: manual 
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-070c0f15d40fd594d
    fsType: ext4  
  #persistentVolumeReclaimPolicy: Recycle
--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: my-ebc-pvc 
spec: 
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 
  volumeName: my-ebs-volume           

  