apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fss-retail-app.fullname" . }}
  labels:
    {{- include "fss-retail-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fss-retail-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fss-retail-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: usernode-js
        image: aryansodhiya12122001/fss-retail-app_kubernetes:latest
        ports:
        - containerPort: 3130
        env:
          # MONGODB_URI from Secret (THIS WAS MISSING/COMMENTED OUT!)
          - name: MONGODB_URI # This is the environment variable name inside the container
            valueFrom:
              secretKeyRef:
                name: mongodb-atlas-uri-secret # Name of your MongoDB URI secret
                key: uri # This is the key within your secret
          # SESSION_SECRET from Secret
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: session_secret
          # EMAIL_USER from Secret
          - name: EMAIL_USER
            valueFrom:
              secretKeyRef:
                name: email-creds
                key: email_user
          # EMAIL_PASS from Secret
          - name: EMAIL_PASS
            valueFrom:
              secretKeyRef:
                name: email-creds
                key: email_pass
          # PORT can remain as a direct value
          - name: PORT # Corrected: added space after hyphen
            value: "3130"
      # NOTE: The 'volumeMounts' and 'volumes' sections for mongo-uri-volume
      # are REMOVED here, as we are relying on the environment variable only.
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fss-retail-app.fullname" . }}-service
  labels:
    {{- include "fss-retail-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 3130
      targetPort: 3130
      protocol: TCP
  selector:
    {{- include "fss-retail-app.selectorLabels" . | nindent 4 }}