apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fss-retail-app.fullname" . }}
  labels:
    {{- include "fss-retail-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fss-retail-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fss-retail-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: usernode-js
        image: aryansodhiya12122001/fss-retail-app_kubernetes:latest
        imagePullPolicy: Always# --- ADDED COMMAND AND ARGS TO ENSURE LOG CAPTURE ---
        command: ["/bin/sh", "-c"]
        args: ["npm start"]
        # --- END OF ADDITION ---
        ports:
        - containerPort: 3130
        env:
          # MONGODB_URI from Secret (THIS WAS MISSING/COMMENTED OUT!)
          # We are now primarily using a volume mount for MONGODB_URI as per server.js logic.
          # The environment variable is kept here as a fallback or if server.js is modified later.
          - name: MONGODB_URI # This is the environment variable name inside the container
            valueFrom:
              secretKeyRef:
                name: mongodb-atlas-uri-secret # Name of your MongoDB URI secret
                key: uri # This is the key within your secret
          # SESSION_SECRET from Secret
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: session_secret
          # EMAIL_USER from Secret
          - name: EMAIL_USER
            valueFrom:
              secretKeyRef:
                name: email-creds
                key: email_user
          # EMAIL_PASS from Secret
          - name: EMAIL_PASS
            valueFrom:
              secretKeyRef:
                name: email-creds
                key: email_pass
          # PORT can remain as a direct value
          - name: PORT
            value: "3130"
        volumeMounts: # ADDED: Volume mounts section
          - name: mongo-uri-volume # This name must match a volume defined below
            mountPath: "/etc/secrets/mongo" # Path inside the container where the secret will be mounted
            readOnly: true # Secrets should typically be read-only
      volumes: # ADDED: Volumes section (at the same level as 'containers')
        - name: mongo-uri-volume # This name must match the volumeMount name
          secret:
            secretName: mongodb-atlas-uri-secret # Name of the Kubernetes Secret
            items:
              - key: uri # The key within the secret that contains the MongoDB URI
                path: uri # The file name inside the 'mountPath' (e.g., /etc/secrets/mongo/uri)
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fss-retail-app.fullname" . }}-service
  labels:
    {{- include "fss-retail-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 3130
      targetPort: 3130
      protocol: TCP
  selector:
    {{- include "fss-retail-app.selectorLabels" . | nindent 4 }}
