
apiVersion: v2 # For Helm 3 charts
name: fss-retail-app # Name of your application/chart
description: A Helm chart for the FSS Retail Application
type: application # Indicates this chart is for an application
version: 0.1.0 # Initial chart version
appVersion: "1.0.0" 