# Default values for retail-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
mongodbAtlasUri: "Aryan%20Sodhiya:Aryan%400506@cluster1.2efxjmw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"
image:
  repository: aryansodhiya12122001/fss-retail-app_kubernetes
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.1"

service:
  type: NodePort # From Service.spec.type
  port: 3130 